services:

  api:
    build:
      context: .
      dockerfile: TransactionAggregation.Api/Dockerfile
    container_name: transaction-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: transaction-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: transactionuser
      POSTGRES_PASSWORD: transactionpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transactionuser -d transactiondb"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4-management
    container_name: transaction-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: transactionuser
      RABBITMQ_DEFAULT_PASS: transactionpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  rabbitmq_data: